"""Worker Tandem supervisor package - provider-neutral foundation (M1-M2).

Modules
-------
models      provider-neutral request/result/config/health/usage/telemetry types
errors      unified error taxonomy + sanitized ``SupervisorRunError``
schemas     canonical PLAN/REVIEW schemas + fail-closed validation helpers
base        ``SupervisorPort`` Protocol + payload normalizers
transport   synchronous, injectable ``httpx`` transport (retries disabled)
fake_adapter deterministic, offline test doubles (no network)

Nothing here is wired into ``worker_tandem_v0.1.2.py`` yet: this milestone is
purely additive and the current Codex path is unchanged.
"""

from .base import (
    ENV_KEY_PREFIX,
    SupervisorPort,
    api_key_env_name,
    key_missing_run_error,
    normalize_plan_payload,
    normalize_review_payload,
    plan_schema,
    resolve_api_key,
    review_schema,
)
from .codex_legacy_adapter import (
    CODEX_CATEGORY_MAP,
    CODEX_PLAN_SCHEMA_NAME,
    CODEX_REASONING_HIGH,
    CODEX_REASONING_LOW,
    CODEX_REASONING_MEDIUM,
    CODEX_REVIEW_SCHEMA_NAME,
    IDENTITY_POLICIES,
    IDENTITY_REJECT,
    IDENTITY_STRIP_STEP_NO,
    PROVIDER_CODEX_LEGACY,
    VALIDATION_ADAPTER,
    VALIDATION_MODES,
    VALIDATION_RUNNER,
    CodexArtifactPaths,
    LegacyCodexSupervisorAdapter,
    StructuredRunnerPort,
    default_codex_paths,
    default_effort_policy,
    translate_codex_exception,
)
from .errors import (
    ALL_CATEGORIES,
    NON_RETRYABLE_CATEGORIES,
    RETRYABLE_CATEGORIES,
    SupervisorError,
    SupervisorRunError,
    category_for_http_status,
    is_retryable_category,
    sanitize_diagnostic,
)
from .fake_adapter import (
    FakeHttpResponse,
    FakeHttpTransport,
    FakeOutcome,
    FakeSupervisorAdapter,
    fake_plan_payload,
    fake_review_payload,
)
from .models import (
    HEALTH_KEY_MISSING,
    HEALTH_READY,
    HEALTH_STATUSES,
    PLAN_OPERATION,
    REVIEW_ARCHITECTURE_DECISION_REQUIRED,
    REVIEW_APPROVE,
    REVIEW_BLOCKED,
    REVIEW_OPERATION,
    REVIEW_REVISE,
    REVIEW_VERDICTS,
    ProviderConfig,
    ProviderHealth,
    ProviderUsage,
    SupervisorPlanRequest,
    SupervisorPlanResult,
    SupervisorReviewRequest,
    SupervisorReviewResult,
    TelemetryRecord,
)
from .deepseek_adapter import (
    DEFAULT_DEEPSEEK_API_BASE,
    DEFAULT_DEEPSEEK_MODEL,
    DEFAULT_DEEPSEEK_TIMEOUT_SEC,
    DEEPSEEK_API_KEY_ENV,
    PROVIDER_DEEPSEEK,
    DeepSeekSupervisorAdapter,
    default_deepseek_config,
    deepseek_endpoint,
    refine_provider_error,
)
from .openai_adapter import (
    DEFAULT_OPENAI_API_BASE,
    DEFAULT_OPENAI_MODEL,
    DEFAULT_OPENAI_TIMEOUT_SEC,
    OPENAI_API_KEY_ENV,
    PROVIDER_OPENAI,
    OpenAISupervisorAdapter,
    classify_openai_error,
    default_openai_config,
    openai_endpoint,
)
from .openai_compatible import (
    CHAT_COMPLETIONS_PATH,
    HEALTH_BY_CATEGORY,
    MODELS_PATH,
    OpenAICompatibleSupervisorAdapter,
    api_endpoint,
    build_chat_completions_body,
    error_haystack,
    extract_message_content,
    health_status_for,
    json_object_system_prompt,
    matches_hints,
    sanitize_key_detail,
    stamp_run_error,
    strict_json_object,
    usage_from_payload,
)
from .router import (
    BUDGET_CHEAP,
    BUDGET_MODES,
    BUDGET_PREMIUM,
    BUDGET_STANDARD,
    CONTRACT_FAILURE_CATEGORIES,
    DEFAULT_HEALTH_TTL_SEC,
    DEFAULT_LEGACY_PROVIDER,
    ID_ANTHROPIC,
    ID_DEEPSEEK,
    ID_OPENAI,
    POLICY_MODE_AUTO,
    POLICY_MODE_MANUAL,
    POLICY_MODES,
    PROVIDER_SIDE_CATEGORIES,
    RETRYABLE_FALLBACK_CATEGORIES,
    SKIP_HEALTH_STATUSES,
    SUPERVISOR_ALL_FAILED_EVENT,
    SUPERVISOR_ERROR_EVENT,
    SUPERVISOR_FALLBACK_EVENT,
    SUPERVISOR_RESULT_EVENT,
    SUPERVISOR_RETRY_EVENT,
    SUPERVISOR_SELECTED_EVENT,
    SupervisorPolicy,
    SupervisorRouter,
    default_auto_policy,
    default_fallback_chain,
    default_risk_routes,
)
from .schemas import (
    CONTROLLER_OWNED_KEYS,
    canonical_json,
    controller_owned_identity_problems,
    extract_json_object,
    payload_hash,
    supervisor_plan_schema,
    supervisor_review_schema,
    validate_against_schema,
    validate_plan_payload,
    validate_review_payload,
)
from .transport import (
    DEFAULT_TIMEOUT_SEC,
    MAX_RESPONSE_BYTES,
    HttpTransport,
    TransportPort,
    TransportResponse,
)

__all__ = [
    # base
    "SupervisorPort",
    "normalize_plan_payload",
    "normalize_review_payload",
    "plan_schema",
    "review_schema",
    # codex_legacy_adapter
    "CODEX_CATEGORY_MAP",
    "CODEX_PLAN_SCHEMA_NAME",
    "CODEX_REASONING_HIGH",
    "CODEX_REASONING_LOW",
    "CODEX_REASONING_MEDIUM",
    "CODEX_REVIEW_SCHEMA_NAME",
    "PROVIDER_CODEX_LEGACY",
    "CodexArtifactPaths",
    "LegacyCodexSupervisorAdapter",
    "StructuredRunnerPort",
    "default_codex_paths",
    "default_effort_policy",
    "translate_codex_exception",
    "IDENTITY_POLICIES",
    "IDENTITY_REJECT",
    "IDENTITY_STRIP_STEP_NO",
    "VALIDATION_ADAPTER",
    "VALIDATION_MODES",
    "VALIDATION_RUNNER",
    # router
    "DEFAULT_LEGACY_PROVIDER",
    "POLICY_MODE_AUTO",
    "POLICY_MODE_MANUAL",
    "SUPERVISOR_ERROR_EVENT",
    "SUPERVISOR_RESULT_EVENT",
    "SUPERVISOR_SELECTED_EVENT",
    "SupervisorPolicy",
    "SupervisorRouter",
    "BUDGET_CHEAP",
    "BUDGET_MODES",
    "BUDGET_PREMIUM",
    "BUDGET_STANDARD",
    "CONTRACT_FAILURE_CATEGORIES",
    "DEFAULT_HEALTH_TTL_SEC",
    "ID_ANTHROPIC",
    "ID_DEEPSEEK",
    "ID_OPENAI",
    "POLICY_MODES",
    "PROVIDER_SIDE_CATEGORIES",
    "RETRYABLE_FALLBACK_CATEGORIES",
    "SKIP_HEALTH_STATUSES",
    "SUPERVISOR_ALL_FAILED_EVENT",
    "SUPERVISOR_FALLBACK_EVENT",
    "SUPERVISOR_RETRY_EVENT",
    "default_auto_policy",
    "default_fallback_chain",
    "default_risk_routes",
    # deepseek_adapter
    "CHAT_COMPLETIONS_PATH",
    "DEFAULT_DEEPSEEK_API_BASE",
    "DEFAULT_DEEPSEEK_MODEL",
    "DEFAULT_DEEPSEEK_TIMEOUT_SEC",
    "DEEPSEEK_API_KEY_ENV",
    "MODELS_PATH",
    "PROVIDER_DEEPSEEK",
    "DeepSeekSupervisorAdapter",
    "default_deepseek_config",
    "deepseek_endpoint",
    "extract_message_content",
    "health_status_for",
    "refine_provider_error",
    "usage_from_payload",
    # openai_adapter
    "DEFAULT_OPENAI_API_BASE",
    "DEFAULT_OPENAI_MODEL",
    "DEFAULT_OPENAI_TIMEOUT_SEC",
    "OPENAI_API_KEY_ENV",
    "PROVIDER_OPENAI",
    "OpenAISupervisorAdapter",
    "classify_openai_error",
    "default_openai_config",
    "openai_endpoint",
    # openai_compatible (shared, M6)
    "HEALTH_BY_CATEGORY",
    "OpenAICompatibleSupervisorAdapter",
    "api_endpoint",
    "build_chat_completions_body",
    "error_haystack",
    "json_object_system_prompt",
    "matches_hints",
    "sanitize_key_detail",
    "stamp_run_error",
    "strict_json_object",
    # base helpers (env key resolution)
    "ENV_KEY_PREFIX",
    "api_key_env_name",
    "key_missing_run_error",
    "resolve_api_key",
    # errors
    "ALL_CATEGORIES",
    "NON_RETRYABLE_CATEGORIES",
    "RETRYABLE_CATEGORIES",
    "SupervisorError",
    "SupervisorRunError",
    "category_for_http_status",
    "is_retryable_category",
    "sanitize_diagnostic",
    # models
    "HEALTH_KEY_MISSING",
    "HEALTH_READY",
    "HEALTH_STATUSES",
    "PLAN_OPERATION",
    "REVIEW_ARCHITECTURE_DECISION_REQUIRED",
    "REVIEW_APPROVE",
    "REVIEW_BLOCKED",
    "REVIEW_OPERATION",
    "REVIEW_REVISE",
    "REVIEW_VERDICTS",
    "ProviderConfig",
    "ProviderHealth",
    "ProviderUsage",
    "SupervisorPlanRequest",
    "SupervisorPlanResult",
    "SupervisorReviewRequest",
    "SupervisorReviewResult",
    "TelemetryRecord",
    # schemas
    "CONTROLLER_OWNED_KEYS",
    "canonical_json",
    "controller_owned_identity_problems",
    "extract_json_object",
    "payload_hash",
    "supervisor_plan_schema",
    "supervisor_review_schema",
    "validate_against_schema",
    "validate_plan_payload",
    "validate_review_payload",
    # transport
    "DEFAULT_TIMEOUT_SEC",
    "MAX_RESPONSE_BYTES",
    "HttpTransport",
    "TransportPort",
    "TransportResponse",
    # fake
    "FakeHttpResponse",
    "FakeHttpTransport",
    "FakeOutcome",
    "FakeSupervisorAdapter",
    "fake_plan_payload",
    "fake_review_payload",
]
